services:
  - type: web
    name: 6a-semana-geofisica
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
